config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :campaigns, :except => [:show]
  get 'chart/index'
  resources :budgets
  resources :categories, :except => [:show] 
  resources :services, :except => [:show]
  resources :books, :except => [:show]
  resources :customers, :except => [:show]
  resources :showad, only: [:show]
  resources :ads, :except => [:show]
  resources :ad_by_category, only: [:show]
  get 'welcome/index'
  #resources :welcome, only: [:show]
  

  devise_for :users
  resources :users, :except => [:show]
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :user, counter_cache: :counter_of_services

	has_many :budget_services, dependent: :restrict_with_exception
	has_many :budgets, through: :budget_services

	validates :name, :description, presence: true
	validates :price, presence: true,  numericality: { greater_than: 0 }
	validates :user_id, presence: true

	monetize :price_cents
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    if params[:q]
      @q = policy_scope(Service).all.ransack(params[:q])
      @services = @q.result.page(params[:page]).per(5)
    else
      @q = Service.none.ransack
      @services = policy_scope(Service).all.page(params[:page]).per(5)
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    authorize @service
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user = current_user
    respond_to do |format|
      if @service.save
        format.html { redirect_to services_url, notice: t('flash.actions.create.notice', model: @service.model_name.human) }
        format.json { render :show, status: :created, location: @service }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to services_url, notice: t('flash.actions.update.notice', model: @service.model_name.human) }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize @service
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: t('flash.actions.destroy.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :price)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <!-- Title if you wanna do it-->
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-6">
        <%= form_with(model: service, local: true, html: { role: 'form' }) do |form| %>
          <% if service.errors.any? %>
            <div id="error_explanation">
                <div class="alert alert-danger" role="alert">
                  <h2><%= t('activerecord.errors.not_saved', :model => service.model_name.human, :count => service.errors.count) %></h2>

                  <ul>
                  <% service.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
            </div>
          <% end %>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-10">
                <%= form.label :description %>
                <%= form.text_area :description, class: "form-control", rows: 5 %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :price %>
                <div class="input-group">
                  <span class="input-group-addon"><%= @service.price.currency.symbol %></span>
                  <%= form.text_field :price, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="actions">
              <div class="col-lg-6">
                <%= form.submit t('helpers.submit.create'), class: "btn btn-success" %>
                <%= link_to t('actions.back'), services_path, class: "btn btn-primary" %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
        <!-- /.col-lg-6 (nested) -->
    </div>
    <!-- /.row (nested) -->
  </div>
  <!-- /.panel-body -->
</div>

app/views/services/create.js.erb
$(function () {
	<% if @service.errors.any? %>
	  bootbox.alert("Erros(s): <%= j @service.errors.full_messages.join('; ') %>")
	<% else %>
	  bootbox.alert("Serviço criado");
	  $('#newServiceModal').modal('hide');
	  window.location.reload();
	<% end %>
});

app/views/services/edit.html.erb
<h1><%= t('actions.edit', model: @service.model_name.human)%> </h1>

<%= render 'form', service: @service %>

app/views/services/index.html.erb
<h1><%= @services.model_name.human.pluralize %></h1>

<div class="panel panel-default">
    <div class="panel-heading">
      <%= search_form_for @q, url: services_path, html: { method: :get } do |s| %>
        <div class="row">
          <div class="col-lg-5">
            <div class="input-group input-group-sm">
              <%= s.search_field :name_or_description_cont, class: "form-control", placeholder: "Nome ou Descrição" %>
              <span class="input-group-btn input-group-sm">
                <%= button_tag type: 'submit', class: "btn btn-success" do %>
                <i class="fa fa-search"></i>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
        
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th><%= @services.human_attribute_name("name") %></th>
                <th><%= @services.human_attribute_name("description") %></th>
                <th><%= @services.human_attribute_name("price") %></th>
                <th><%= t('helpers.submit.actions') %></th>
              </tr>
            </thead>

            <tbody>
              <% @services.each do |service| %>
                <tr>
                  <td><%= service.name %></td>
                  <td><%= service.description %></td>
                  <td><%= humanized_money_with_symbol(service.price) %></td>
                  <td class="col-md-2"><%= link_to edit_service_path(service), class: "btn btn-info btn-circle" do %> <i class="fa fa-edit"></i><% end %>
                    <%= link_to service_path(service), method: :delete, class: "btn btn-danger btn-circle", data: { confirm: t('confirm') } do %> <i class="fa fa-minus"></i><% end %> </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <br>

        <%= link_to t('actions.new', model: @services.model_name.human), new_service_path, class: "btn btn-primary" %>
    </div>
</div>

<div class="row">
  <div class="text-center">
    <%= paginate @services %>
  </div>
</div>

app/views/services/new.html.erb
<h1><%= t('actions.new', model: @service.model_name.human)%> </h1>

<%= render 'form', service: @service %>

app/views/services/new.js.erb
$(function () {
	$('#newServiceModal').modal();
});

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Price cents:</strong>
  <%= @service.price_cents %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>