config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :campaigns, :except => [:show]
  get 'chart/index'
  resources :budgets
  resources :categories, :except => [:show] 
  resources :services, :except => [:show]
  resources :books, :except => [:show]
  resources :customers, :except => [:show]
  resources :showad, only: [:show]
  resources :ads, :except => [:show]
  resources :ad_by_category, only: [:show]
  get 'welcome/index'
  #resources :welcome, only: [:show]
  

  devise_for :users
  resources :users, :except => [:show]
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord

  has_one_attached :picture

  belongs_to :user, counter_cache: :counter_of_ads
  belongs_to :category

  validates :title, :description, :contact, presence: true
  validates :user_id, presence: true
  validates :category_id, presence: true

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.street_changed? || obj.city_changed? || obj.state_changed? || obj.country_changed? }

  after_validation :verify_location, on: [ :create, :update ]

  def address
  	[street, city, state, country].compact.join(', ')
  end

  def verify_location 
  	if self.latitude.blank? || self.longitude.blank?
  	  self.errors.add :base, :verify_location
  	end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :cep, :street, :neighborhood, :city, :state, presence: true 
  validates :email, presence: true, format: Devise.email_regexp
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, counter_cache: :counter_of_books
  belongs_to :customer

  validates_with ScheduleValidator

  validates :description, :status, :customer_id, presence: true
  validates :schedule, presence: true
  validates :user_id, presence: true

  enum status: [ :pending, :processing, :done ]

  def self.search_by_date(initialdate, finaldate)
  	if initialdate.present? && finaldate.present?
  		where("schedule BETWEEN ? AND ?", initialdate.to_date.beginning_of_day, finaldate.to_date.end_of_day)
  	elsif finaldate.present?
  		where("schedule <= ?", finaldate.to_date.beginning_of_day)
  	elsif initialdate.present?
  		where("schedule >= ?", initialdate.to_date.beginning_of_day)
  	end
  end

  def self.status_attributes_for_select
    statuses.map do |status, s|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.statuses.#{status}"), status]
    end
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :customer
  belongs_to :user, counter_cache: :counter_of_budgets
  
  has_many :budget_services, dependent: :destroy
  has_many :services, through: :budget_services

  validates :customer_id, :duedate, presence: true
  validates :totalprice, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :discount, numericality: { greater_than_or_equal_to: 0 }
  validates :user_id, presence: true
  validates_associated :budget_services

  before_save :set_total_price, on: [ :create, :update ]

  monetize :totalprice_cents
  monetize :discount_cents

  accepts_nested_attributes_for :budget_services, reject_if: :all_blank, allow_destroy: true

  private
    def set_total_price
    	total = 0
    	self.budget_services.each do |budget_service|
    	  total += budget_service.service.price
    	end

      if self.discount <= total
        total -= self.discount
      else
        total = 0
      end

    	self.totalprice = total
    end
end

app/models/budget_service.rb
class BudgetService < ApplicationRecord
  belongs_to :budget
  belongs_to :service
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	belongs_to :user, counter_cache: :counter_of_campaigns

	has_many :campaign_customer, dependent: :destroy
	has_many :customers, through: :campaign_customer

	validates :title, :body, presence: true

	after_save :schedule_mail

	private

	def schedule_mail
	  @customers = Customer.where(user_id: self.user_id)
	  @customers.each do |customer|
	  	CampaignCustomer.create(campaign: self, customer: customer)
	  	CampaignJob.perform_now(customer, self.title, self.body)
	  end
	end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  has_many :ads, dependent: :restrict_with_exception
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user, counter_cache: true

  has_many :phones, dependent: :destroy
  has_many :books, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :campaign_customer, dependent: :destroy
  has_many :campaigns, through: :campaign_customer

  validates_with CpfCnpjValidator

  validates :name, :cpf, presence: true
  validates :cpf, length: { in: 11..14 }
  validates :user_id, presence: true
  validates_associated :address

  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :customer

  validates :customer_id, :number, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :user, counter_cache: :counter_of_services

	has_many :budget_services, dependent: :restrict_with_exception
	has_many :budgets, through: :budget_services

	validates :name, :description, presence: true
	validates :price, presence: true,  numericality: { greater_than: 0 }
	validates :user_id, presence: true

	monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  #:registerable
  enum role: [ :admin, :customer ]

  has_many :ads, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :campaigns, dependent: :destroy

  after_create :send_welcome_email


  private

  def send_welcome_email
    WelcomeUserJob.perform_now(self)
  end 
end

app/helpers/ads_helper.rb
module AdsHelper
  def cities
  	cities = CS.cities(:rj, :br)
  	cities
  end

  def state 
  	state = ['Rio de Janeiro']
  	state
  end

  def country
  	country = ['Brasil']
  	country
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_datetime(value)
  	date = value.strftime("%d/%m/%Y %H:%M")
  	date
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def formatted_date(value)
  	date = value.strftime("%d/%m/%Y")
  	date
  end
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/showad_helper.rb
module ShowadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def distance(lat, long, latitude, longitude)
		Geocoder::Calculations.distance_between([lat,long], [latitude,longitude]).round(2)
	end
end

app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to "Encontre-me", home_index_path, class: "navbar-brand" %> 
    
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right" id="menu-nav">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
          <li><%= link_to edit_user_path(current_user) do %> <i class="fa fa-gear"></i> Conta <% end %></a>
          <li class="divider"></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %> <i class="fa fa-sign-out"></i> Sair<% end %></a>
          </li>
      </ul>
    </li>
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li class="active">
          <a href="#" id="menu-link"><i class="fa fa-angle-double-right"></i> Menu de Opções<span class="fa arrow"></span></a> <ul class="nav nav-second-level collapse in" aria-expanded="true"> 
            <li>
              <% if policy(current_user).index? %>
                  <%= link_to users_path do %>
                    <i class="fa fa-users"></i> Users
                  <% end %>
              <% end %>
            </li>
            <li>
              <% if policy(current_user).index? %>
                <%= link_to categories_path do %>
                  <i class="fa fa-table"></i> Categorias
                <% end %>
              <% end %>
            </li>
            <li>
                <%= link_to ads_path do %>
                  <i class="fa fa-list"></i> Meus Anúncios
                <% end %>
            </li>
            <li>
                <%= link_to customers_path do %>
                  <i class="fa fa-exchange"></i> Meus Clientes
                <% end %>
            </li>
            <li>
                <%= link_to books_path do %>
                  <i class="fa fa-book"></i> Minha Agenda
                <% end %>
            </li>
            <li>
                <%= link_to services_path do %>
                  <i class="fa fa-tasks"></i> Meus Serviços
                <% end %>
            </li>
            <li>
                <%= link_to budgets_path do %>
                  <i class="fa fa-money"></i> Meus Orçamentos
                <% end %>
            </li>
            <li>
                <%= link_to campaigns_path do %>
                  <i class="fa fa-envelope "></i> Minhas Campanhas
                <% end %>
            </li>
            <li>
                <%= link_to chart_index_path do %>
                  <i class="fa fa-bar-chart-o"></i> Relatórios Gráficos
                <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>              
</nav>

          	
          	

app/views/modals/_ad_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="adModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> </h4>
      </div>
      <div class="modal-body">
        <ul class="list-group">
          <li class="list-group-item" id="ad_description"></li>
          <li class="list-group-item" id="ad_contact"></li>
          <li class="list-group-item" id="ad_email"></li>
          <li class="list-group-item" id="ad_street"></li>
          <li class="list-group-item" id="ad_city"></li>
          <li class="list-group-item" id="ad_state"></li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary"" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/modals/_new_customer_modal.html.erb
<div class="modal fade" id="newCustomerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('actions.new', model: @customer.model_name.human)%></h4>
      </div>
      <div class="modal-body">
        <%= form_with(model: @customer, remote: true, html: { role: 'form' }) do |form| %>

          <% if @customer.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger" role="alert">
                <h2><%= t('activerecord.errors.not_saved', :model => customer.model_name.human, :count => customer.errors.count) %></h2>

                <ul>
                <% @customer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            </div>
          <% end %>
      

          <div class="row">
            <div class="form-group">
              <div class="col-lg-10">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control", placeholder: "Nome do Cliente" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :cpf %>
                <%= form.text_field :cpf, class: "form-control", placeholder: "CPF do Cliente" %>
              </div>
            </div>
          </div>

          <hr>
          <div id="phones">
            <%= form.fields_for :phones do |phone| %>
              <%= render 'customers/phones/phone_fields', :f => phone %>
            <% end %>

            <div class="links">
              <%= link_to_add_association 'Novo Telef.', form, :phones, partial: 'customers/phones/phone_fields', class: "btn btn-primary btn-xs" %>
            </div>
          </div>
          <hr>

          <%= form.fields_for :address do |ff| %>
            <div class="row">
              <div class="form-group">
                <div class="col-lg-6">
                  <%= ff.label :cep %>
                  <%= ff.text_field :cep, class: "form-control", placeholder: "CEP" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-lg-10">
                  <%= ff.label :street %>
                  <%= ff.text_field :street, class: "form-control", placeholder: "Nome da Rua" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-lg-8">
                  <%= ff.label :neighborhood %>
                  <%= ff.text_field :neighborhood, class: "form-control", placeholder: "Bairro" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-lg-6">
                  <%= ff.label :city %>
                  <%= ff.select :city, options_for_select(cities, selected: @customer.address.city), {}, class: "form-control" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-lg-6">
                  <%= ff.label :state %>
                  <%= ff.select :state, options_for_select(state, selected: @customer.address.state), {}, class: "form-control" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-lg-10">
                  <%= ff.label :email %>
                  <%= ff.text_field :email, class: "form-control", placeholder: "exemplo@email.com" %>
                </div>
              </div>
            </div>

          <% end %>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <%= submit_tag t('helpers.submit.create'), class: "btn btn-primary" %>
          </div>
        
        <% end %>


      </div>
    </div>
  </div>
</div>

app/views/modals/_new_service_modal.html.erb
<div class="modal fade" id="newServiceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('actions.new', model: @service.model_name.human)%></h4>
      </div>
      <div class="modal-body">

      	<%= form_with(model: @service, remote: true, html: { role: 'form' }) do |form| %>
          <% if @service.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

              <ul>
              <% @service.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control", placeholder: "Nome do Serviço" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-10">
                <%= form.label :description %>
                <%= form.text_area :description, class: "form-control", placeholder: "Descrição do Serviço", rows: 5 %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :price %>
                <div class="input-group">
                  <span class="input-group-addon"><%= @service.price.currency.symbol %></span>
                  <%= form.text_field :price, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>


          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <%= submit_tag "Enviar", class: "btn btn-primary" %>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>