config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :campaigns, :except => [:show]
  get 'chart/index'
  resources :budgets
  resources :categories, :except => [:show] 
  resources :services, :except => [:show]
  resources :books, :except => [:show]
  resources :customers, :except => [:show]
  resources :showad, only: [:show]
  resources :ads, :except => [:show]
  resources :ad_by_category, only: [:show]
  get 'welcome/index'
  #resources :welcome, only: [:show]
  

  devise_for :users
  resources :users, :except => [:show]
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :customer
  belongs_to :user, counter_cache: :counter_of_budgets
  
  has_many :budget_services, dependent: :destroy
  has_many :services, through: :budget_services

  validates :customer_id, :duedate, presence: true
  validates :totalprice, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :discount, numericality: { greater_than_or_equal_to: 0 }
  validates :user_id, presence: true
  validates_associated :budget_services

  before_save :set_total_price, on: [ :create, :update ]

  monetize :totalprice_cents
  monetize :discount_cents

  accepts_nested_attributes_for :budget_services, reject_if: :all_blank, allow_destroy: true

  private
    def set_total_price
    	total = 0
    	self.budget_services.each do |budget_service|
    	  total += budget_service.service.price
    	end

      if self.discount <= total
        total -= self.discount
      else
        total = 0
      end

    	self.totalprice = total
    end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  before_action :set_models_to_modal, only: [:show, :edit, :update, :new, :create]

  # GET /budgets
  # GET /budgets.json
  def index
    if params[:q]
      @q = policy_scope(Budget).all.ransack(params[:q])
      @budgets = @q.result.includes(:customer).page(params[:page]).per(5)
    else
      @q = Budget.none.ransack
      @budgets = policy_scope(Budget).all.page(params[:page]).per(5)
    end
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
    authorize @budget
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    @budget.user = current_user
    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_url, notice: t('flash.actions.create.notice', model: @budget.model_name.human) }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budgets_url, notice: t('flash.actions.update.notice', model: @budget.model_name.human) }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    authorize @budget
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: t('flash.actions.destroy.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    def set_models_to_modal
      @customer = Customer.new
      @customer.build_address
      @service = Service.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:customer_id, :duedate, :totalprice, :discount, service_ids: [], budget_services_attributes: [:id, :budget_id, :service_id, :_destroy])
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def formatted_date(value)
  	date = value.strftime("%d/%m/%Y")
  	date
  end
end

app/views/budgets/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <!-- Title if you wanna do it-->
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-6">
        <%= form_with(model: budget, local: true, rule: 'form') do |form| %>
          <% if budget.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger" role="alert">
                <h2><%= t('activerecord.errors.not_saved', :model => budget.model_name.human, :count => budget.errors.count) %></h2>
                <ul>
                <% budget.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul> 
              </div>
            </div>
          <% end %>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-8">
                <%= form.label :customer_id %>
                <div class="input-group">
                  <span class="input-group-addon"><%= link_to new_customer_path, class: "btn-link", remote: true do %> <i class="fa fa-plus"></i></span><% end %>
                  <%= form.select(:customer_id, Customer.where(user_id: current_user.id ).collect {|p| [ p.name, p.id ] }, {prompt: "Selecione o cliente"}, { class: "form-control" })%>
                </div>
              </div>
            </div>
          </div>


          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :duedate %>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  <%= form.text_field :duedate, class: "form-control", id: "datepicker" %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :service %>
                <div class="input-group">
                  <span class="input-group-addon"><%= link_to new_service_path, class: "btn-link", remote: true do %> <i class="fa fa-plus"></i></span><% end %>
                  <%= form.select(:service_ids, Service.where(user_id: current_user.id ).collect {|p| [ p.name, p.id ] }, {}, { class: "form-control", id: "select_menu", multiple: true  })%>
                </div>
              </div>
            </div>
          </div>
          
          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :totalprice %>
                <div class="input-group">
                  <span class="input-group-addon"><%= @budget.totalprice.currency.symbol %></span>
                  <%= form.text_field :totalprice, class: "form-control", readonly: true %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :discount %>
                <div class="input-group">
                  <span class="input-group-addon"><%= @budget.discount.currency.symbol %></span>
                  <%= form.text_field :discount, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="actions">
              <div class="col-lg-6">
                <%= form.submit t('helpers.submit.create'), class: "btn btn-success" %>
                <%= link_to t('actions.back'), budgets_path, class: "btn btn-primary" %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
        <!-- /.col-lg-6 (nested) -->
    </div>
    <!-- /.row (nested) -->
  </div>
  <!-- /.panel-body -->
</div>

<%= render partial: "modals/new_customer_modal" %> 
<%= render partial: "modals/new_service_modal" %> 

app/views/budgets/edit.html.erb
<h1><%= t('actions.edit', model: @budget.model_name.human)%> </h1>

<%= render 'form', budget: @budget %>

app/views/budgets/index.html.erb
<h1><%= @budgets.model_name.human.pluralize %></h1>

<div class="panel panel-default">
    <div class="panel-heading">
      <%= search_form_for @q, url: budgets_path, html: { method: :get } do |b| %>
      <div class="row">
        <div class="col-lg-5">
          <div class="input-group input-group-sm">
            <%= b.search_field :customer_name_or_customer_cpf_cont, class: "form-control", placeholder: "Nome ou CPF do cliente" %>
            <span class="input-group-btn input-group-sm">
              <%= button_tag type: 'submit', class: "btn btn-success" do %>
              <i class="fa fa-search"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>  
        
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th><%= @budgets.human_attribute_name("customer") %></th>
                <th><%= @budgets.human_attribute_name("duedate") %></th>
                <th><%= @budgets.human_attribute_name("totalprice") %></th>
                <th><%= @budgets.human_attribute_name("discount") %></th>
                <th><%= t('helpers.submit.actions') %></th>
              </tr>
            </thead>

            <tbody>
              <% @budgets.each do |budget| %>
                <tr>
                  <td><%= budget.customer.name %></td>
                  <td><%= formatted_date(budget.duedate) %></td>
                  <td><%= budget.totalprice %></td>
                  <td><%= budget.discount %></td>
                  <td class="col-md-2"><%= link_to edit_budget_path(budget), class: "btn btn-info btn-circle" do %> <i class="fa fa-edit"></i><% end %>
                    <%= link_to budget_path(budget), method: :delete, class: "btn btn-danger btn-circle", data: { confirm: t('confirm') } do %> <i class="fa fa-minus"></i><% end %> 
                    <%= link_to budget_path(budget, format: :pdf), class: "btn btn-warning btn-circle" do %> <i class="fa fa-file-pdf-o"></i><% end %> </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <br>

        <%= link_to t('actions.new', model: @budgets.model_name.human), new_budget_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/budgets/new.html.erb
<h1><%= t('actions.new', model: @budget.model_name.human)%> </h1>

<%= render 'form', budget: @budget %>

app/views/budgets/substituirnomultiselect.html.erb
<div id="budgetservices">
            <%= form.fields_for :budget_services do |budget_service| %>
              <%= render 'budgets/budget_services/budget_services_fields', :f => budget_service %>
            <% end %>

            <div class="links">
              <%= link_to_add_association '+ Serviço', form, :budget_services, partial: 'budgets/budget_services/budget_services_fields', class: "btn btn-primary btn-xs" %>
            </div>
          </div>
          <br>