config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :campaigns, :except => [:show]
  get 'chart/index'
  resources :budgets
  resources :categories, :except => [:show] 
  resources :services, :except => [:show]
  resources :books, :except => [:show]
  resources :customers, :except => [:show]
  resources :showad, only: [:show]
  resources :ads, :except => [:show]
  resources :ad_by_category, only: [:show]
  get 'welcome/index'
  #resources :welcome, only: [:show]
  

  devise_for :users
  resources :users, :except => [:show]
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  has_many :ads, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = policy_scope(Category).all.page(params[:page]).per(5)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    authorize @category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: t('flash.actions.create.notice', model: @category.model_name.human) }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: t('flash.actions.update.notice', model: @category.model_name.human) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    authorize @category
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('flash.actions.destroy.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <!-- Title if you wanna do it--> 
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-6">

        <%= form_with(model: category, local: true, html: { role: 'form' }) do |form| %>
          <% if category.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger" role="alert">
                <h2><%= t('activerecord.errors.not_saved', :model => category.model_name.human, :count => category.errors.count) %></h2>

                <ul>
                <% category.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            </div>
          <% end %>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-6">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>


          <div class="row">
            <div class="actions">
              <div class="col-lg-6">
                <%= form.submit t('helpers.submit.create'), class: "btn btn-success" %>
                <%= link_to t('actions.back'), categories_path, class: "btn btn-primary" %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
        <!-- /.col-lg-6 (nested) -->
    </div>
    <!-- /.row (nested) -->
  </div>
  <!-- /.panel-body -->
</div>

app/views/categories/edit.html.erb
<h1><%= t('actions.edit', model: @category.model_name.human)%> </h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1><%= @categories.model_name.human.pluralize %></h1>

<div class="panel panel-default">
  <div class="panel-heading"> </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th><%= @categories.human_attribute_name("name") %></th>
            <th><%= @categories.human_attribute_name("user") %></th>
            <th><%= t('helpers.submit.actions') %></th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.user.name %></td>
              <td class="col-md-2"><%= link_to edit_category_path(category), class: "btn btn-info btn-circle" do %> <i class="fa fa-edit"></i><% end %>
                <%= link_to category_path(category), method: :delete, class: "btn btn-danger btn-circle", data: { confirm: t('confirm') } do %> <i class="fa fa-minus"></i><% end %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br> 

      <%= link_to t('actions.new(a)', model: @categories.model_name.human), new_category_path, class: "btn btn-primary" %> 
 
    </div>
</div>

<div class="row">
  <div class="text-center">
    <%= paginate @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<h1><%= t('actions.new(a)', model: @category.model_name.human)%> </h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.user %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>